
service: 
  name: numpy-test
  publish: false # disable auto-publishing to the Serverless platform

## Order is important
plugins:
  # - '@kingdarboja/serverless-plugin-typescript'
  - serverless-python-requirements
  # - serverless-plugin-typescript
  # - serverless-python-individually

custom:
  pythonRequirements:
    # dockerizePip: non-linux
    dockerizePip: true
    # zip: true
    # slim: true
  # pyIndividually:
    # wrap:pyfunc: lambdas/pyfunc/handler.main     # mapping to the real handler

  typeScript:
    tsconfigFilePath: ./tsconfig.json

package:
  individually: true
  exclude:
    - node_modules/**
    - .build/**
    - lambdas/pyfunc/venv/**
    - lambdas/pyfunc/__pycache__/**

provider:
  name: aws
  # runtime: nodejs12.x
  # environment:
  #   PYTHONPATH: '/var/task/vendored:/var/runtime'

functions:

  pyfunc:
    ## Invoke local OK, invoke remote KO
    # # handler: handler.main
    # handler: lambdas/pyfunc/handler.main
    # runtime: python3.6
    # module: lambdas/pyfunc

    # handler: handler.main
    handler: lambdas/pyfunc/handler.main
    runtime: python3.6
    # module: lambdas/pyfunc

  tsfunc:
    handler: lambdas/tsfunc/handler.hello
    runtime: nodejs12.x


# functions:

#   pyfunc:
#     handler: lambdas/pyfunc/wrap.handler
#     runtime: python3.6
#     package:
#       include:
#         - lambdas/pyfunc/**

